require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IpAddressesController do

  # This should return the minimal set of attributes required to create a valid
  # IpAddress. As you add validations to IpAddress, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IpAddressesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ip_addresses as @ip_addresses" do
      ip_address = IpAddress.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ip_addresses).should eq([ip_address])
    end
  end

  describe "GET show" do
    it "assigns the requested ip_address as @ip_address" do
      ip_address = IpAddress.create! valid_attributes
      get :show, {:id => ip_address.to_param}, valid_session
      assigns(:ip_address).should eq(ip_address)
    end
  end

  describe "GET new" do
    it "assigns a new ip_address as @ip_address" do
      get :new, {}, valid_session
      assigns(:ip_address).should be_a_new(IpAddress)
    end
  end

  describe "GET edit" do
    it "assigns the requested ip_address as @ip_address" do
      ip_address = IpAddress.create! valid_attributes
      get :edit, {:id => ip_address.to_param}, valid_session
      assigns(:ip_address).should eq(ip_address)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IpAddress" do
        expect {
          post :create, {:ip_address => valid_attributes}, valid_session
        }.to change(IpAddress, :count).by(1)
      end

      it "assigns a newly created ip_address as @ip_address" do
        post :create, {:ip_address => valid_attributes}, valid_session
        assigns(:ip_address).should be_a(IpAddress)
        assigns(:ip_address).should be_persisted
      end

      it "redirects to the created ip_address" do
        post :create, {:ip_address => valid_attributes}, valid_session
        response.should redirect_to(IpAddress.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ip_address as @ip_address" do
        # Trigger the behavior that occurs when invalid params are submitted
        IpAddress.any_instance.stub(:save).and_return(false)
        post :create, {:ip_address => {  }}, valid_session
        assigns(:ip_address).should be_a_new(IpAddress)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        IpAddress.any_instance.stub(:save).and_return(false)
        post :create, {:ip_address => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ip_address" do
        ip_address = IpAddress.create! valid_attributes
        # Assuming there are no other ip_addresses in the database, this
        # specifies that the IpAddress created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        IpAddress.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => ip_address.to_param, :ip_address => { "these" => "params" }}, valid_session
      end

      it "assigns the requested ip_address as @ip_address" do
        ip_address = IpAddress.create! valid_attributes
        put :update, {:id => ip_address.to_param, :ip_address => valid_attributes}, valid_session
        assigns(:ip_address).should eq(ip_address)
      end

      it "redirects to the ip_address" do
        ip_address = IpAddress.create! valid_attributes
        put :update, {:id => ip_address.to_param, :ip_address => valid_attributes}, valid_session
        response.should redirect_to(ip_address)
      end
    end

    describe "with invalid params" do
      it "assigns the ip_address as @ip_address" do
        ip_address = IpAddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IpAddress.any_instance.stub(:save).and_return(false)
        put :update, {:id => ip_address.to_param, :ip_address => {  }}, valid_session
        assigns(:ip_address).should eq(ip_address)
      end

      it "re-renders the 'edit' template" do
        ip_address = IpAddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IpAddress.any_instance.stub(:save).and_return(false)
        put :update, {:id => ip_address.to_param, :ip_address => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ip_address" do
      ip_address = IpAddress.create! valid_attributes
      expect {
        delete :destroy, {:id => ip_address.to_param}, valid_session
      }.to change(IpAddress, :count).by(-1)
    end

    it "redirects to the ip_addresses list" do
      ip_address = IpAddress.create! valid_attributes
      delete :destroy, {:id => ip_address.to_param}, valid_session
      response.should redirect_to(ip_addresses_url)
    end
  end

end
